Repository Cornerstone-CICCC/web-2-final-project-wysiwyg, pull requests merged in 2025-01, with the labels that each got.

#6 [FEAT] Added Social Component
  final-project/src/assets/icons/ic_dribbble.svg
  final-project/src/assets/icons/ic_facebook.svg
  final-project/src/assets/icons/ic_insta.svg
  final-project/src/assets/icons/ic_linkedin.svg
  final-project/src/assets/icons/ic_twitter.svg
  final-project/src/components/Social.astro
Labels: enhancement

#23 Logos Component
  final-project/src/assets/img/logo1.png
  final-project/src/assets/img/logo2.png
  final-project/src/assets/img/logo3.png
  final-project/src/assets/img/logo4.png
  final-project/src/assets/img/logo5.png
  final-project/src/assets/img/logo6.png
  final-project/src/assets/img/logo7.png
  final-project/src/components/Logos.astro
Labels: enhancement

#7 [FEAT] Added Footer Component and Updated Layout
  final-project/src/assets/ddsgnr_logo.svg
  final-project/src/assets/icon/chat.svg
  final-project/src/assets/icon/email.svg
  final-project/src/assets/icon/location.svg
  final-project/src/assets/icon/phone.svg
  final-project/src/assets/icons/ic_dribbble.svg
  final-project/src/assets/icons/ic_facebook.svg
  final-project/src/assets/icons/ic_insta.svg
  final-project/src/assets/icons/ic_linkedin.svg
  final-project/src/assets/icons/ic_twitter.svg
  final-project/src/assets/img/logo1.png
  final-project/src/assets/img/logo2.png
  final-project/src/assets/img/logo3.png
  final-project/src/assets/img/logo4.png
  final-project/src/assets/img/logo5.png
  final-project/src/assets/img/logo6.png
  final-project/src/assets/img/logo7.png
  final-project/src/components/Container.astro
  final-project/src/components/Footer.astro
  final-project/src/components/Home/ContactUs.astro
  final-project/src/components/Logos.astro
  final-project/src/components/Social.astro
  final-project/src/layouts/Layout.astro
  final-project/src/pages/index.astro
  final-project/src/styles/global.css
  package-lock.json
Labels: enhancement, dependent, do not merge

#22 About Us Component
  final-project/src/assets/img/video.jpg
  final-project/src/components/AboutUs.astro
Labels: enhancement

#19 Faqs Component
  final-project/src/components/Faqs.astro
Labels: enhancement

#15 Text classes and responsiveness
  final-project/src/styles/global.css
Labels: enhancement

#14 [FEAT] Header Component
  final-project/src/assets/img/page-logo.svg
  final-project/src/components/Header.astro
  final-project/src/components/header/Hamburger.astro
  final-project/src/components/header/Info.astro
  final-project/src/components/header/Logo.astro
  final-project/src/components/header/Menu.astro
Labels: enhancement

#25 [FEAT] Testimonials Slider
  final-project/astro.config.mjs
  final-project/package-lock.json
  final-project/package.json
  final-project/src/assets/icons/arrow-left.svg
  final-project/src/assets/icons/arrow-right.svg
  final-project/src/assets/icons/chevron-right.svg
  final-project/src/assets/icons/webflow.svg
  final-project/src/components/Testimonials/Slider.astro
  final-project/src/components/Testimonials/Testimonial.astro
  final-project/src/components/Testimonials/Testimonials.astro
  final-project/src/styles/global.css
  final-project/tsconfig.json
Labels: enhancement

#16 [FEAT] Our mission component
  final-project/src/assets/mission.png
  final-project/src/components/Mission.astro
Labels: enhancement

#34 [FEAT] Added Meta Component
  final-project/public/favicon.svg
  final-project/src/layouts/Layout.astro
  final-project/src/pages/index.astro
Labels: enhancement

#35 Fixing Component Styles
  final-project/src/components/AboutUs.astro
  final-project/src/components/Banner.astro
  final-project/src/components/Faqs.astro
  final-project/src/components/Logos.astro
  final-project/src/styles/global.css
Labels: enhancement

#48 [FEAT] Homepage
  final-project/src/components/AboutUs.astro
  final-project/src/components/ContactForm.astro
  final-project/src/components/ContactUs.astro
  final-project/src/components/Faqs.astro
  final-project/src/components/Layout/Section.astro
  final-project/src/components/Schedule.astro
  final-project/src/components/Testimonials/Testimonials.astro
  final-project/src/components/header/Info.astro
  final-project/src/components/header/Menu.astro
  final-project/src/components/team/Team.astro
  final-project/src/layouts/Layout.astro
  final-project/src/pages/index.astro
  final-project/src/styles/global.css
Labels: enhancement, dependent
